services:
  - type: web
    name: melbourne-celebrant-api
    env: python
    buildCommand: |
      echo "Installing backend dependencies..."
      pip install -r celebrant-portal-v2/backend/requirements.txt
      echo "Running database migrations..."
      cd celebrant-portal-v2/backend && python migrate.py
      echo "Installing Node.js and frontend dependencies..."
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      cd celebrant-portal-v2/frontend
      npm install
      NEXT_PUBLIC_API_URL=https://amelbournecelebrant-6ykh.onrender.com npm run build
    startCommand: |
      cd celebrant-portal-v2/backend
      python -c "
import subprocess
import threading
import time

def start_backend():
    subprocess.run(['python', '-m', 'uvicorn', 'app.main:app', '--host', '0.0.0.0', '--port', '8000'])

def start_frontend():
    time.sleep(2)  # Wait for backend to start
    subprocess.run(['npx', 'serve', '../frontend/out', '-l', '3000'])

# Start backend in background
backend_thread = threading.Thread(target=start_backend)
backend_thread.daemon = True
backend_thread.start()

# Start frontend
start_frontend()
"
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: melbourne-celebrant-db
          property: connectionString
      - key: NEXT_PUBLIC_API_URL
        value: https://amelbournecelebrant-6ykh.onrender.com

databases:
  - name: melbourne-celebrant-db
    databaseName: celebrant_portal
    user: celebrant_user 