"""Initial migration with updated models

Revision ID: 3238d133395c
Revises: 
Create Date: 2025-06-23 23:43:08.713877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3238d133395c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ceremony_templates', sa.Column('is_shared', sa.Boolean(), nullable=True))
    op.add_column('ceremony_templates', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_index('idx_template_name', table_name='ceremony_templates')
    op.drop_index('idx_template_type', table_name='ceremony_templates')
    op.create_index('idx_template_name_org', 'ceremony_templates', ['name', 'organization_id'], unique=False)
    op.create_index('idx_template_org', 'ceremony_templates', ['organization_id'], unique=False)
    op.create_index('idx_template_shared', 'ceremony_templates', ['is_shared'], unique=False)
    op.create_index('idx_template_type_org', 'ceremony_templates', ['ceremony_type', 'organization_id'], unique=False)
    op.create_foreign_key(None, 'ceremony_templates', 'organizations', ['organization_id'], ['id'])
    op.add_column('compliance_alerts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('compliance_alerts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('compliance_alerts', 'couple_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('compliance_alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('compliance_alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index('idx_alerts_org_resolved', 'compliance_alerts', ['organization_id', 'is_resolved'], unique=False)
    op.create_index('idx_alerts_severity', 'compliance_alerts', ['severity'], unique=False)
    op.create_foreign_key(None, 'compliance_alerts', 'users', ['resolved_by'], ['id'])
    op.alter_column('couples', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_ceremony_date', table_name='couples')
    op.drop_index('idx_couple_status', table_name='couples')
    op.drop_index('idx_partner_emails', table_name='couples')
    op.drop_index('idx_partner_names', table_name='couples')
    op.create_index('idx_couple_date_org', 'couples', ['ceremony_date', 'organization_id'], unique=False)
    op.create_index('idx_couple_names_org', 'couples', ['partner1_name', 'partner2_name', 'organization_id'], unique=False)
    op.create_index('idx_couple_org', 'couples', ['organization_id'], unique=False)
    op.create_index('idx_couple_status_org', 'couples', ['status', 'organization_id'], unique=False)
    op.create_foreign_key(None, 'couples', 'organizations', ['organization_id'], ['id'])
    op.add_column('import_sessions', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('import_sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('idx_import_created', table_name='import_sessions')
    op.drop_index('idx_import_status', table_name='import_sessions')
    op.create_index('idx_import_session_org', 'import_sessions', ['organization_id'], unique=False)
    op.create_index('idx_import_session_status', 'import_sessions', ['status'], unique=False)
    op.create_index('idx_import_session_user', 'import_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'import_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'import_sessions', 'organizations', ['organization_id'], ['id'])
    op.add_column('imported_names', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.drop_index('idx_imported_date', table_name='imported_names')
    op.drop_index('idx_imported_names', table_name='imported_names')
    op.drop_index('idx_imported_processed', table_name='imported_names')
    op.create_index('idx_imported_names_org', 'imported_names', ['partner1_name', 'partner2_name', 'organization_id'], unique=False)
    op.create_index('idx_imported_org', 'imported_names', ['organization_id'], unique=False)
    op.create_index('idx_imported_processed_org', 'imported_names', ['is_processed', 'organization_id'], unique=False)
    op.create_foreign_key(None, 'imported_names', 'organizations', ['organization_id'], ['id'])
    op.add_column('legal_form_submissions', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('legal_form_submissions', sa.Column('submitted_by', sa.String(length=100), nullable=True))
    op.add_column('legal_form_submissions', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('legal_form_submissions', sa.Column('is_validated', sa.Boolean(), nullable=True))
    op.add_column('legal_form_submissions', sa.Column('validated_by', sa.Integer(), nullable=True))
    op.add_column('legal_form_submissions', sa.Column('validated_at', sa.DateTime(), nullable=True))
    op.alter_column('legal_form_submissions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('legal_form_submissions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'not_started'"))
    op.alter_column('legal_form_submissions', 'legal_deadline',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index('idx_legal_forms_couple_type', 'legal_form_submissions', ['couple_id', 'form_type'], unique=False)
    op.create_index('idx_legal_forms_deadline', 'legal_form_submissions', ['legal_deadline'], unique=False)
    op.create_index('idx_legal_forms_org_status', 'legal_form_submissions', ['organization_id', 'status'], unique=False)
    op.create_foreign_key(None, 'legal_form_submissions', 'users', ['validated_by'], ['id'])
    op.drop_column('legal_form_submissions', 'submission_date')
    op.drop_column('legal_form_submissions', 'file_name')
    op.drop_column('legal_form_submissions', 'validation_status')
    op.add_column('organizations', sa.Column('slug', sa.String(length=50), nullable=False))
    op.add_column('organizations', sa.Column('domain', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('subdomain', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('contact_name', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('address_line1', sa.String(length=200), nullable=True))
    op.add_column('organizations', sa.Column('address_line2', sa.String(length=200), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('abn', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('business_name', sa.String(length=200), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('organizations', sa.Column('date_format', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('subscription_plan', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('max_users', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('max_couples', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('max_templates', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('is_trial', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.alter_column('organizations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('idx_org_active', 'organizations', ['is_active'], unique=False)
    op.create_index('idx_org_domain', 'organizations', ['domain'], unique=False)
    op.create_index('idx_org_slug', 'organizations', ['slug'], unique=False)
    op.create_index('idx_org_subdomain', 'organizations', ['subdomain'], unique=False)
    op.create_unique_constraint(None, 'organizations', ['subdomain'])
    op.create_unique_constraint(None, 'organizations', ['slug'])
    op.create_unique_constraint(None, 'organizations', ['domain'])
    op.drop_column('organizations', 'description')
    op.drop_column('organizations', 'address')
    op.add_column('reminder_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('reminder_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('reminder_logs', 'form_submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_reminders_org_sent', 'reminder_logs', ['organization_id', 'sent_at'], unique=False)
    op.create_index('idx_reminders_status', 'reminder_logs', ['delivery_status'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_username', table_name='users')
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_email_org', 'users', ['email', 'organization_id'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_unique_constraint('uq_user_email_org', 'users', ['email', 'organization_id'])
    op.create_unique_constraint('uq_user_username_org', 'users', ['username', 'organization_id'])
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('uq_user_username_org', 'users', type_='unique')
    op.drop_constraint('uq_user_email_org', 'users', type_='unique')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email_org', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_index('idx_reminders_status', table_name='reminder_logs')
    op.drop_index('idx_reminders_org_sent', table_name='reminder_logs')
    op.alter_column('reminder_logs', 'form_submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reminder_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('reminder_logs', 'error_message')
    op.add_column('organizations', sa.Column('address', sa.TEXT(), nullable=True))
    op.add_column('organizations', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_index('idx_org_subdomain', table_name='organizations')
    op.drop_index('idx_org_slug', table_name='organizations')
    op.drop_index('idx_org_domain', table_name='organizations')
    op.drop_index('idx_org_active', table_name='organizations')
    op.alter_column('organizations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('organizations', 'trial_ends_at')
    op.drop_column('organizations', 'is_trial')
    op.drop_column('organizations', 'max_templates')
    op.drop_column('organizations', 'max_couples')
    op.drop_column('organizations', 'max_users')
    op.drop_column('organizations', 'subscription_plan')
    op.drop_column('organizations', 'date_format')
    op.drop_column('organizations', 'currency')
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'business_name')
    op.drop_column('organizations', 'abn')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'postal_code')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'address_line2')
    op.drop_column('organizations', 'address_line1')
    op.drop_column('organizations', 'contact_name')
    op.drop_column('organizations', 'subdomain')
    op.drop_column('organizations', 'domain')
    op.drop_column('organizations', 'slug')
    op.add_column('legal_form_submissions', sa.Column('validation_status', sa.VARCHAR(length=50), nullable=True))
    op.add_column('legal_form_submissions', sa.Column('file_name', sa.VARCHAR(length=255), nullable=True))
    op.add_column('legal_form_submissions', sa.Column('submission_date', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'legal_form_submissions', type_='foreignkey')
    op.drop_index('idx_legal_forms_org_status', table_name='legal_form_submissions')
    op.drop_index('idx_legal_forms_deadline', table_name='legal_form_submissions')
    op.drop_index('idx_legal_forms_couple_type', table_name='legal_form_submissions')
    op.alter_column('legal_form_submissions', 'legal_deadline',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('legal_form_submissions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'not_started'"))
    op.alter_column('legal_form_submissions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('legal_form_submissions', 'validated_at')
    op.drop_column('legal_form_submissions', 'validated_by')
    op.drop_column('legal_form_submissions', 'is_validated')
    op.drop_column('legal_form_submissions', 'file_type')
    op.drop_column('legal_form_submissions', 'submitted_by')
    op.drop_column('legal_form_submissions', 'submitted_at')
    op.drop_constraint(None, 'imported_names', type_='foreignkey')
    op.drop_index('idx_imported_processed_org', table_name='imported_names')
    op.drop_index('idx_imported_org', table_name='imported_names')
    op.drop_index('idx_imported_names_org', table_name='imported_names')
    op.create_index('idx_imported_processed', 'imported_names', ['is_processed'], unique=False)
    op.create_index('idx_imported_names', 'imported_names', ['partner1_name', 'partner2_name'], unique=False)
    op.create_index('idx_imported_date', 'imported_names', ['ceremony_date'], unique=False)
    op.drop_column('imported_names', 'organization_id')
    op.drop_constraint(None, 'import_sessions', type_='foreignkey')
    op.drop_constraint(None, 'import_sessions', type_='foreignkey')
    op.drop_index('idx_import_session_user', table_name='import_sessions')
    op.drop_index('idx_import_session_status', table_name='import_sessions')
    op.drop_index('idx_import_session_org', table_name='import_sessions')
    op.create_index('idx_import_status', 'import_sessions', ['status'], unique=False)
    op.create_index('idx_import_created', 'import_sessions', ['created_at'], unique=False)
    op.drop_column('import_sessions', 'user_id')
    op.drop_column('import_sessions', 'organization_id')
    op.drop_constraint(None, 'couples', type_='foreignkey')
    op.drop_index('idx_couple_status_org', table_name='couples')
    op.drop_index('idx_couple_org', table_name='couples')
    op.drop_index('idx_couple_names_org', table_name='couples')
    op.drop_index('idx_couple_date_org', table_name='couples')
    op.create_index('idx_partner_names', 'couples', ['partner1_name', 'partner2_name'], unique=False)
    op.create_index('idx_partner_emails', 'couples', ['partner1_email', 'partner2_email'], unique=False)
    op.create_index('idx_couple_status', 'couples', ['status'], unique=False)
    op.create_index('idx_ceremony_date', 'couples', ['ceremony_date'], unique=False)
    op.alter_column('couples', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'compliance_alerts', type_='foreignkey')
    op.drop_index('idx_alerts_severity', table_name='compliance_alerts')
    op.drop_index('idx_alerts_org_resolved', table_name='compliance_alerts')
    op.alter_column('compliance_alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('compliance_alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('compliance_alerts', 'couple_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('compliance_alerts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('compliance_alerts', 'updated_at')
    op.drop_constraint(None, 'ceremony_templates', type_='foreignkey')
    op.drop_index('idx_template_type_org', table_name='ceremony_templates')
    op.drop_index('idx_template_shared', table_name='ceremony_templates')
    op.drop_index('idx_template_org', table_name='ceremony_templates')
    op.drop_index('idx_template_name_org', table_name='ceremony_templates')
    op.create_index('idx_template_type', 'ceremony_templates', ['ceremony_type'], unique=False)
    op.create_index('idx_template_name', 'ceremony_templates', ['name'], unique=False)
    op.drop_column('ceremony_templates', 'organization_id')
    op.drop_column('ceremony_templates', 'is_shared')
    # ### end Alembic commands ###
