"""Add Invoice model for payment tracking

Revision ID: 4acd1bf8b6b1
Revises: 3238d133395c
Create Date: 2025-06-24 01:51:16.091840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acd1bf8b6b1'
down_revision = '3238d133395c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('proof_of_payment_path', sa.String(length=500), nullable=True),
    sa.Column('proof_of_payment_filename', sa.String(length=255), nullable=True),
    sa.Column('proof_of_payment_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('proof_of_payment_verified', sa.Boolean(), nullable=False),
    sa.Column('proof_of_payment_verified_by', sa.Integer(), nullable=True),
    sa.Column('proof_of_payment_verified_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('reminder_sent_7_days', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent_1_day', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent_overdue', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['proof_of_payment_verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('idx_invoice_couple', 'invoices', ['couple_id'], unique=False)
    op.create_index('idx_invoice_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index('idx_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('idx_invoice_org', 'invoices', ['organization_id'], unique=False)
    op.create_index('idx_invoice_status', 'invoices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_invoice_status', table_name='invoices')
    op.drop_index('idx_invoice_org', table_name='invoices')
    op.drop_index('idx_invoice_number', table_name='invoices')
    op.drop_index('idx_invoice_due_date', table_name='invoices')
    op.drop_index('idx_invoice_couple', table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
