"""Add CeremonyTemplate model

Revision ID: 9b52895cbd06
Revises: 
Create Date: 2025-06-21 17:10:43.567124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b52895cbd06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ceremony_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ceremony_type', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('celebrant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celebrant_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('couple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner1_name', sa.String(length=100), nullable=False),
    sa.Column('partner1_email', sa.String(length=120), nullable=False),
    sa.Column('partner1_phone', sa.String(length=20), nullable=True),
    sa.Column('partner2_name', sa.String(length=100), nullable=False),
    sa.Column('partner2_email', sa.String(length=120), nullable=False),
    sa.Column('partner2_phone', sa.String(length=20), nullable=True),
    sa.Column('ceremony_date', sa.DateTime(), nullable=True),
    sa.Column('ceremony_location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('celebrant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celebrant_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ceremony',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('ceremony_type', sa.String(length=50), nullable=True),
    sa.Column('template_content', sa.Text(), nullable=True),
    sa.Column('custom_vows', sa.Text(), nullable=True),
    sa.Column('readings', sa.Text(), nullable=True),
    sa.Column('music', sa.Text(), nullable=True),
    sa.Column('rehearsal_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couple.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['ceremony_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('ceremony')
    op.drop_table('couple')
    op.drop_table('ceremony_template')
    op.drop_table('user')
    # ### end Alembic commands ###
