services:
  - type: web
    name: melbourne-celebrant-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        value: oav542oj7_XvU5sW8o-ypCZ_hTpyQ9EWLBmgku1v1Jk
      - key: DATABASE_URL
        value: postgresql://celebrant_user:TY8Z95faU56JQ5q4MnhRjtd05hEpAPTJ@dpg-d1dv3ap5pdvs73b0s3o0-a:5432/celebrant_portal
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 30 