services:
  - type: web
    name: melbourne-celebrant-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python test_imports.py && gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: melbourne-celebrant-db
          property: connectionString
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 30

databases:
  - name: melbourne-celebrant-db
    databaseName: celebrant_portal
    user: celebrant_user 